version: '3.7'
services:
  redis:
    image: redis
    command: redis-server --port 6379
    container_name: go_redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
