// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {menu} from '../models';

export function AddTodo(arg1:string):Promise<backend.Todo>;

export function CreateMenu():Promise<menu.Menu>;

export function DeleteTodo(arg1:string):Promise<Array<backend.Todo>>;

export function ExportTodos():Promise<void>;

export function GetTodos():Promise<Array<backend.Todo>>;

export function ImportTodos():Promise<Array<backend.Todo>>;

export function ToggleTodo(arg1:string):Promise<Array<backend.Todo>>;
