// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['backend']['App']['AddTodo'](arg1);
}

export function CreateMenu() {
  return window['go']['backend']['App']['CreateMenu']();
}

export function DeleteTodo(arg1) {
  return window['go']['backend']['App']['DeleteTodo'](arg1);
}

export function ExportTodos() {
  return window['go']['backend']['App']['ExportTodos']();
}

export function GetTodos() {
  return window['go']['backend']['App']['GetTodos']();
}

export function ImportTodos() {
  return window['go']['backend']['App']['ImportTodos']();
}

export function ToggleTodo(arg1) {
  return window['go']['backend']['App']['ToggleTodo'](arg1);
}
