apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgAvEPj1ZFhPAVgq8gSv5YYl2ytW350/E31R88TvAFFI02lqmJeTJxjO9ShLp3QO/QE7lfDUUi6JzZtfafbSkGPoLiXFiygoFl1+ZQEWpcZBmwlh/xhSgEDO6hTI9rorNkaxX/Tl9bmNIDfOM+T4CLu+3jOwQdrfpD5TyQN3dSnLAn7cSCRilK/ILNBLAdUCJG7sXWrdH5tvR9/m4PH5jwt5cAOs1EeS6P2G3qAi7Zss0i7GmALrNOoDY9KWYiDCAmS/hn4aHW5Qh7VHv3nl3hJDQcX2GDIlKLHzap/nq92txoXoORYb3cCiQ/CFplJdDQ8GgxLuD6StRqeFjuFcYY9l95wOxSf0M/FMPVziA2qdku4lF9uaqgwU/7Bx8xLRj3CY7UlyQmpDqQ1Y956l73WIJJd+9vEp8ba4r/vZSs29tWeshAXSqqV9woJTc4tN3XfjS9xscJppTeMKFhjKth4RG2pLBpdMnu0p2OdTpNax6khGoLzeZrI/GPBUy4rWNwRchlQgxBpM8oWs2tb5uyKMh0VG3zUdXmpvoGSXTgYTKeBQ9bF2nLtib0yXELBd6CQIF5yVn+LGPo6I7KsAeqI7NysPH2SubVqrX5ao8SjAKnNsms5rzecoWsgjgly8nAITdF21/Svsge2+A8JR+nnAQj5noMEpva1FzQoViWXTEeD8gc2h9tuY5XOs7wtpWKvVBmH1W+hGJ9GM+Q==
    username: AgDOAvDkXyfpxqTu87NpRcVmqdDiZ0jf7WWgRelq07mQQGQxtbbl7Wrxj6tOt2tL+XT4WrKd1zY6n4aTmLjQ2rQBDFLeddEdpuZiVpK5pBROxoxyUiDAtg9OjB9s6IU1DkG67GT4KD4ufCLRIyYN9mlJwnQ8PPiFByiYzN8Dw+sub36o61AtQ6qmgmrwp3Fb2dscfnUInfNfISyveO8UrUGBQTqV7z+M3ZnSU7HetwQPq0yI/Q6xYiGKiSDG5vj5AAff2Orv+DGjkbHKNhV6wTTrX/yonjszZSoReEg6TIr1y7H6Mfe+ZJi4i962vdJQrtHzWktFpW+Jgq67m2j/dvP0UppK8bCFWsi1C+DYnc6QfVAluRrwN6aiodhA3GVQVtnGVIN7fR/VQg6R4O9hy0wMRllf+cBpf3LGi+f5R4PfkD5Ha2Di3JAm30M8cS262s3MZwVTbkV66h9VaKdQ1+GsOWelNUjdmQ8rkqvnARh2INbclEB/mHpWDNI7wrWZRtyt2p2uHuo25pN6Xjl2yxJGJcLn1YlAClwVUwEo9c6oQ85sWk5CBL8ZcN9LwQpOTMa8J8003N3POMdu4EYFxKkVLHfVQL5McOq+qyGYEuZhZIcC/OoeILvwQCzXKhfk4uoFBDyJ+jCcogetHadpHu6KViMNPc6k2H3JCRcIw5hIrQw1u6f/kUpJeM6m6O9K/7cZH8JX2Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

