apiVersion: v1
kind: Service
metadata:
  name: my-mysql-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      nodePort: 33306
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: my-mysql
    app.kubernetes.io/name: mysql
