version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: go-mongo-mongodb
    environment:
      - MONGO_INITDB_DATABASE=go-mongo
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - ${HOME}/data/docker/${MONGO_INITDB_DATABASE}:/data/db
    ports:
      - 27017:27017
    command: [--auth]
    restart: unless-stopped
