// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package downcaser

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockdowncaser creates a new instance of mockdowncaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdowncaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdowncaser {
	mock := &mockdowncaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdowncaser is an autogenerated mock type for the downcaser type
type mockdowncaser struct {
	mock.Mock
}

type mockdowncaser_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdowncaser) EXPECT() *mockdowncaser_Expecter {
	return &mockdowncaser_Expecter{mock: &_m.Mock}
}

// Downcase provides a mock function for the type mockdowncaser
func (_mock *mockdowncaser) Downcase(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Downcase")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdowncaser_Downcase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Downcase'
type mockdowncaser_Downcase_Call struct {
	*mock.Call
}

// Downcase is a helper method to define mock.On call
//   - s string
func (_e *mockdowncaser_Expecter) Downcase(s interface{}) *mockdowncaser_Downcase_Call {
	return &mockdowncaser_Downcase_Call{Call: _e.mock.On("Downcase", s)}
}

func (_c *mockdowncaser_Downcase_Call) Run(run func(s string)) *mockdowncaser_Downcase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdowncaser_Downcase_Call) Return(s1 string, err error) *mockdowncaser_Downcase_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *mockdowncaser_Downcase_Call) RunAndReturn(run func(s string) (string, error)) *mockdowncaser_Downcase_Call {
	_c.Call.Return(run)
	return _c
}
