// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageService creates a new instance of MockMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageService {
	mock := &MockMessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageService is an autogenerated mock type for the MessageService type
type MockMessageService struct {
	mock.Mock
}

type MockMessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageService) EXPECT() *MockMessageService_Expecter {
	return &MockMessageService_Expecter{mock: &_m.Mock}
}

// SendChargeNotification provides a mock function for the type MockMessageService
func (_mock *MockMessageService) SendChargeNotification(n int) error {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for SendChargeNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageService_SendChargeNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChargeNotification'
type MockMessageService_SendChargeNotification_Call struct {
	*mock.Call
}

// SendChargeNotification is a helper method to define mock.On call
//   - n int
func (_e *MockMessageService_Expecter) SendChargeNotification(n interface{}) *MockMessageService_SendChargeNotification_Call {
	return &MockMessageService_SendChargeNotification_Call{Call: _e.mock.On("SendChargeNotification", n)}
}

func (_c *MockMessageService_SendChargeNotification_Call) Run(run func(n int)) *MockMessageService_SendChargeNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageService_SendChargeNotification_Call) Return(err error) *MockMessageService_SendChargeNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageService_SendChargeNotification_Call) RunAndReturn(run func(n int) error) *MockMessageService_SendChargeNotification_Call {
	_c.Call.Return(run)
	return _c
}
