version: '3.7'

services:
  redis7001:
    image: redis:6
    container_name: redis7001
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7001/data:/data
    ports:
      - "7001:7001"
      - "17001:17001"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis7002:
    image: redis:6
    container_name: redis7002
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7002/data:/data
    ports:
      - "7002:7002"
      - "17002:17002"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis7003:
    image: redis:6
    container_name: redis7003
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7003/data:/data
    ports:
      - "7003:7003"
      - "17003:17003"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis7004:
    image: redis:6
    container_name: redis7004
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7004/data:/data
    ports:
      - "7004:7004"
      - "17004:17004"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis7005:
    image: redis:6
    container_name: redis7005
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7005/data:/data
    ports:
      - "7005:7005"
      - "17005:17005"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  redis7006:
    image: redis:6
    container_name: redis7006
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7006/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7006/data:/data
    ports:
      - "7006:7006"
      - "17006:17006"
    environment:
      # Set the time zone to Shanghai, otherwise the time will be problematic
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: '100m'
        max-file: '10'

networks:
  app_net:
    external: true
