basePath: /
info:
  contact: {}
  description: Echo API Server.
  title: Echo API
  version: "1.0"
paths:
  /echo:
    get:
      description: Echo API
      operationId: EchoHandler
      responses:
        "200":
          description: Request 값을 그대로 반환한다
          schema:
            type: string
      summary: Echo API
      tags:
      - Echo
  /ping:
    get:
      description: Ping API
      operationId: PingHandler.Ping
      responses:
        "200":
          description: pong 메시지를 리턴한다
          schema:
            type: string
      summary: Ping API
      tags:
      - Ping
swagger: "2.0"
