listen: :8080
tasks:
  - name: "task1"
    description: "this is a test"
  - name: "task2"
    description: "this is a test"
redis:
  mode: cluster #standalone, cluster
serverList:
  - localhost:1001
  - localhost:1002
  - localhost:1003
