version: "3"
services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: article_management_api
#    ports:
#      - 9090:9090
#    depends_on:
#      mysql:
#        condition: service_healthy
#    volumes:
#      - ./config.json:/app/config.json

  mysql:
    image: mysql:5.7 
    container_name: go-clean-arch-mysql
#    command: mysqld --user=root
    volumes:
      - ${HOME}/data/docker/go-clean-arch-mysql:/var/lib/mysql
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=article
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
