// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockDoer
func (_mock *MockDoer) Do(n int, s string) error {
	ret := _mock.Called(n, s)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(n, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - n int
//   - s string
func (_e *MockDoer_Expecter) Do(n interface{}, s interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", n, s)}
}

func (_c *MockDoer_Do_Call) Run(run func(n int, s string)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(err error) *MockDoer_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(n int, s string) error) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}
