name: Automated Code Review
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
  issue_comment:
  workflow_call:
    inputs:
      ignore_glob:
        description: "Glob pattern to ignore files"
        required: false
        default: "['**/mocks/**', 'docs/**']"
        type: string

jobs:
  pr_agent_job:
    uses: kenshin579/actions/.github/workflows/code-review.yml@main
    secrets: inherit
