name: Label Merge Conflict

on:
  pull_request:
    branches:
    - master

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
    - name: Label Conflicting Pull Requests
      uses: eps1lon/actions-label-merge-conflict@v2.0.0
      with:
        dirtyLabel: "PR: needs rebase"
        removeOnDirtyLabel: "PR: ready to ship"
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
        commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."